name: CI

on:
  push:
  schedule:
    - cron: '*/5 * * * *'
    #- cron: '17 9 * * *'

jobs:
  ci-job-schedule:
    name: ci-job-schedule

    runs-on: ubuntu-latest

    steps:
    - name: "git checkout"
      uses: actions/checkout@v4
      with: { ref: main }

    - name: "log date"
      run: |
        date
        git log -1

    - name: "build and post thread wet run"
      env:
        user_id: ${{ secrets.user_id }}
        token:   ${{ secrets.token   }}
      run: |
        chmod +x ./run.sh
        ./run.sh

