name: CI
#on:
#  schedule:              # note that gh schedules usually start a few minutes late
#  - cron: '17  9 * * *'  # 9:17 UTC time (just after ~5 AM eastern depending on dst) every day
#  - cron: '*/5 * * * *'  # every 5 minutes, or as fast as gh will run
on: [push]

jobs:
  ci-job:
    name: ci-job

    runs-on: ubuntu-latest

    steps:
    - name: "git checkout"
      uses: actions/checkout@v4
      with: { ref: main }

    - name: "log date"
      run: |
        date
        git log -1

    - name: "build and post thread"
      env:
        user_id: ${{ secrets.user_id }}
        token:   ${{ secrets.token   }}
      run: |
        chmod +x ./run.sh
        ./run.sh

