
name: "main github action"
on:
  schedule:
    - cron: '*/5 * * * *'
    #- cron: '45 * * * *'
    #- cron: '* * * * *'
    #- cron: '30 5 * * 1,3'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: "main step"
        env: 
          user_id: ${{ secrets.user_id }}
          token:   ${{ secrets.token   }}
        run: |
          echo "starting github action"
          g++ -o main main.cpp
          ./main

