name: CI

on:
  push:
  schedule:
    - cron: '*/5 * * * *'
    #- cron: '17 9 * * *'

jobs:
  ci-job-schedule:
    name: ci-job-schedule

    runs-on: ubuntu-latest

    steps:
    - name: "git checkout"
      uses: actions/checkout@v4
      with: { ref: main }

    - name: "log date"
      run: |
        date
        git log -1

    - name: "post thread wet run"
      env:
        user_id: ${{ secrets.user_id }}
        token:   ${{ secrets.token   }}
      if: github.event.push == true
      run: |
        chmod +x ./run.sh
        ./run.sh --dry
      else:
      run: |
        chmod +x ./run.sh
        ./run.sh

#    steps:
#      - name: Not on Monday or Wednesday
#        if: github.event.schedule != '30 5 * * 1,3'
#        run: echo "This step will be skipped on Monday and Wednesday"
#      - name: Every time
#        run: echo "This step will always run"


