
name: "main github action"
#on:
#  schedule:
#    - cron: '*/20 * * * *'
#    #- cron: '45 * * * *'
#    #- cron: '* * * * *'
#    #- cron: '30 5 * * 1,3'
on: [push]

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: "main step"
        uses: actions/checkout@v3
        env: 
          user_id: ${{ secrets.user_id }}
          token:   ${{ secrets.token   }}
        run: |
          echo "starting github action"
          ls
          pwd
          g++ -o main main.cpp
          ./main
          chmod +x ./run.sh
          ./run.sh

