name: CI
on: 
  schedule:
  - cron: '*/5 * * * *'

jobs:
  job1:
    name: scheduled_job

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with: { ref: main }
      #with: { ref: debug }

    - name: List files
      run: |
        ls
        date
        git status
        git log -1

    - name: "build and post thread"
      env: 
        user_id: ${{ secrets.user_id }}
        token:   ${{ secrets.token   }}
      run: |
        echo "starting github action"
        ls
        pwd
        g++ -o main main.cpp
        ./main
        chmod +x ./run.sh
        ./run.sh

#name: "prime-of-the-day action"
#on:
#  schedule:
#    - cron: '*/5 * * * *'
#    #- cron: '45 * * * *'
#    #- cron: '* * * * *'
#    #- cron: '30 5 * * 1,3'
##on: [push]
#
#jobs:
#  scheduled_job:
#    runs-on: ubuntu-latest
#    steps:
#
#      - uses: actions/checkout@v3
#
#      - name: "build and post thread"
#        env: 
#          user_id: ${{ secrets.user_id }}
#          token:   ${{ secrets.token   }}
#        run: |
#          echo "starting github action"
#          ls
#          pwd
#          g++ -o main main.cpp
#          ./main
#          chmod +x ./run.sh
#          ./run.sh
#
#name: "prime-of-the-day action"
#on: [push]
#
#jobs:
#  push_job:
#    runs-on: ubuntu-latest
#    steps:
#
#      - uses: actions/checkout@v3
#
#      - name: "build and post thread"
#        env: 
#          user_id: ${{ secrets.user_id }}
#          token:   ${{ secrets.token   }}
#        run: |
#          echo "starting github action"
#          ls
#          pwd
#          g++ -o main main.cpp
#          ./main
#          chmod +x ./run.sh
#          #./run.sh
#
