name: CI
#on:
#  schedule:  # 9:17 UTC time (~4 AM eastern) every day
#  - cron: '17 9 * * *'
#  #- cron: '*/5 * * * *'
on: [push]

jobs:
  ci-job:
    name: ci-job

    runs-on: ubuntu-latest

    steps:
    - name: "git checkout"
      uses: actions/checkout@v3
      with: { ref: main }

    - name: "log date"
      run: |
        date
        git log -1

    - name: "build and post thread"
      env:
        user_id: ${{ secrets.user_id }}
        token:   ${{ secrets.token   }}
      run: |
        chmod +x ./run.sh
        ./run.sh

