name: CI

on:
  push:
  schedule:
    - cron: '17 9 * * *'
    #- cron: '*/5 * * * *'

jobs:
  ci-job:
    name: ci-job

    runs-on: ubuntu-latest

    steps:
    - name: "git checkout"
      uses: actions/checkout@v4
      with: { ref: main }

    - name: "log date"
      run: |
        date
        git log -1

    - name: "post thread dry run"
      if: github.event.schedule != '17 9 * * *'
      env:
        user_id: ${{ secrets.user_id }}
        token:   ${{ secrets.token   }}
      run: |
        chmod +x ./run.sh
        ./run.sh --dry

    - name: "post thread wet run"
      if: github.event.schedule == '17 9 * * *'
      env:
        user_id: ${{ secrets.user_id }}
        token:   ${{ secrets.token   }}
      run: |
        echo github.event.push
        chmod +x ./run.sh
        ./run.sh

