name: CI
on:
  schedule:
  - cron: '*/5 * * * *'
  #- cron: '17 9 * * *'

## can there be separators on-push and on-schedule jobs?  it would be nice to
## always have dry runs on push for debugging
#on: [push]

jobs:
  ci-job:
    name: ci-job

    runs-on: ubuntu-latest

    steps:
    - name: "git checkout"
      uses: actions/checkout@v4
      with: { ref: main }

    - name: "log date"
      run: |
        date
        git log -1

    - name: "build and post thread"
      env:
        user_id: ${{ secrets.user_id }}
        token:   ${{ secrets.token   }}
      run: |
        chmod +x ./run.sh
        ./run.sh

